version: "2"

volumes:
   db:
   
services:
   
    db:
        image: mariadb:latest
        restart: unless-stopped
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
        volumes:
            - db:/var/lib/mysql
        env_file:
            - db.env
    
    redis:
        image: redis:latest
        restart: unless-stopped
        command: redis-server --requirepass redis_pwd
    
    app:
        build: ./app
        restart: unless-stopped
        volumes: &vol_mount
            - ./volumes/base:/var/www/html
            - ./volumes/config:/var/www/html/config
            - ./volumes/apps:/var/www/html/apps
            - ./volumes/data:/var/www/html/data
            - ./volumes/custom_apps:/var/www/html/custom_apps
#             - /etc/localtime:/etc/localtime:ro
            - ./volumes/xdebug:/xdebug
        depends_on:
            - db
            - redis
        env_file:
            - db.env
        environment:
            MYSQL_HOST: db
            NEXTCLOUD_ADMIN_USER: admin
            NEXTCLOUD_ADMIN_PASSWORD: admin_pwd
            REDIS_HOST: redis
            REDIS_HOST_PASSWORD: redis_pwd
            DEBUG_USER_ID: 1000
#            PHP_MEMORY_LIMIT: 2G
        ports:
            - 8000:80
    
    cli:
        build: ./app
        restart: 'no'
        volumes: *vol_mount
        entrypoint: []
        command: ['/bin/bash']

   
